[language-server]
angular-ls = {command = "ngserver", args = ["--stdio", "--tsProbeLocations", ".", "--ngProbeLocations", ".",]}

[[language]]
name ="html"
language-servers = ["angular-ls","vscode-html-language-server"]

[[language]]
name = "typescript"
language-servers = ["angular-ls","typescript-language-server"]
