#!/bin/sh

PWD=$(pwd)
DEV_COMPOSE_FILE="$PROJECT_DIR/compose.dev.yml"

cleanup() {
  docker compose -f $DEV_COMPOSE_FILE down
  cd $PWD
  exit 0
}

trap "cleanup" INT

docker compose -f $DEV_COMPOSE_FILE up -d

cd "$PROJECT_DIR/application"
mvn mvn spring-boot:run -Dspring-boot.run.profiles=dev

cleanup
